### ISSUE TITLE
Add support for fallback language and namespace.

### ISSUE THREAD

**Issue by CuddleBunny** [DarkLiKally/I18Next.Net#4]
For example when given:

translation.json
```
{ "test": "Test Entry" }
```

more.json
```
{ "other": "Other Entry" }
```

The use of `Localize["more:test"]` should fall back to the value of `"Test Entry"` instead of `"test"`. As described in the [i18next docs](https://www.i18next.com/principles/translation-resolution#resolution-order).

**Comment by CuddleBunny** [comment]
I may have some time to create a PR next week if you'd like assistance.

**Comment by DarkLiKally** [comment]
Hello CuddleBunny,

thanks for your feedback, you're right that functionality should be implemented!

Very busy in my life now, starting custom business and such. Sorry for responding that late to your issue. Would be nice if you could assist me a bit with development until everything's settled on my side. 
I'm working on a Unity Engine integration at my side because we're having a game project where we need a solid internationalization library.

If you're busy too right now, I'll schedule the issue on my internal plan. Thanks again for your response.

**Comment by CuddleBunny** [comment]
Thanks for the response. I got moved to another project but when I get switched back to this one I will come back and address this. Not sure about the timeline though so don't wait up for me if you get bored one day.

**Comment by DarkLiKally** [comment]
Ok, thank you :) Maybe I've some time the next days.

**Comment by Shaddix** [comment]
@DarkLiKally could you please check out the PR for fallback language support?
Thanks!

**Comment by Shaddix** [comment]
@DarkLiKally is there any chance to get your feedback on that? :) sorry to bother

**Comment by DarkLiKally** [comment]
Merged your changes :)

**Comment by Shaddix** [comment]
Thanks a lot!

**Comment by DarkLiKally** [comment]
Changes are included in the latest release pushed to nuget!
